#!/usr/bin/env python3
"""Generate the browser simulator's idle art, from the same sources as the firmware's.

Writes firmware/simulator/idle_art.js: the sleeping cat's five poses and the link-down
icon as white-on-transparent PNG data URIs, plus where the firmware puts them on the
480 px panel. The simulator tints them with a CSS mask.

Needs Pillow and rsvg-convert.   Usage: python3 gen_simulator_assets.py
"""

from __future__ import annotations

import base64
import importlib.util
import io
import json
import re
import sys
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OUT = ROOT / "firmware" / "simulator" / "idle_art.js"
FACE = ROOT / "firmware" / "main" / "face_cover.h"


def load(name: str):
    spec = importlib.util.spec_from_file_location(name, HERE / f"{name}.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


cat_tool = load("gen_idle_cat")
linkdown_tool = load("gen_linkdown_icon")


def face(name: str) -> int:
    return int(re.search(rf"{name}\s*=\s*(\d+)", FACE.read_text()).group(1))


def centered_y(height: int) -> int:
    """face_cover.c: centered between the message line and the dock top, on an even pixel."""
    y = (face("FACE_MESSAGE_Y") + 28 + _dock_top() - height) // 2
    return y - y % 2


def _dock_top() -> int:
    return (
        face("FACE_SCREEN")
        - face("FACE_EDGE")
        - face("FACE_DOCK_INSET")
        - face("FACE_DOCK_GAP")
        - face("FACE_BTN_H")
    )


def data_uri(alpha: Image.Image) -> str:
    white = Image.new("RGBA", alpha.size, (255, 255, 255, 0))
    white.putalpha(alpha)
    buf = io.BytesIO()
    white.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def art() -> dict:
    cat = cat_tool.build()
    poses = {"rest": (0, 0), "ear1": (1, 0), "ear2": (2, 0), "tail1": (0, 1), "tail2": (0, 2)}
    icon = linkdown_tool.render()
    box_w = face("FACE_LINKDOWN_W")
    box_h = icon.height + face("FACE_LINKDOWN_GAP") + face("FACE_LINKDOWN_CAPTION_H")
    return {
        "cat": {
            "w": cat.canvas.w,
            "h": cat.canvas.h,
            "x": (480 - cat.canvas.w) // 2,
            "y": centered_y(cat.canvas.h),
        },
        "frames": {
            name: data_uri(cat_tool.compose(cat, ear=e, tail=t)) for name, (e, t) in poses.items()
        },
        "linkdown": {
            "x": (480 - box_w) // 2,
            "y": centered_y(box_h),
            "w": box_w,
            "h": box_h,
            "icon": icon.width,
            "gap": face("FACE_LINKDOWN_GAP"),
            "image": data_uri(icon),
        },
    }


def main() -> None:
    OUT.write_text(
        "/* Generated by firmware/scripts/gen_simulator_assets.py. Do not edit. */\n"
        "const IDLE_ART = " + json.dumps(art(), indent=1) + ";\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}, {OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
