#!/usr/bin/env python3
"""Generate the idle screen's sleeping cat for the panel (A8 alpha images).

Reads the five frames in docs/branding/ginger-idle-anim (white on transparent) and
writes firmware/main/idle_cat_geom.h and firmware/main/idle_cat.c.

The cat is one still image with two holes, plus a small patch per pose for each
hole: three for the ear, three for the tail. Showing a pose swaps one patch, so
the panel redraws only that patch's box, never the whole cat. Every box starts and
ends on an even pixel because the CO5300 takes even-sized windows.

Needs Pillow.   Usage: python3 gen_idle_cat.py
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
FRAMES = ROOT / "docs" / "branding" / "ginger-idle-anim"
MAIN = ROOT / "firmware" / "main"

POSES = {
    "ear": ["rest", "ear1", "ear2"],
    "tail": ["rest", "tail1", "tail2"],
}
CANVAS_PAD = 4
PATCH_PAD = 2
# The frames are drawn on a 480 px canvas at full size. The panel shows the cat smaller.
SCALE = 0.7


@dataclass(frozen=True)
class Box:
    x: int
    y: int
    w: int
    h: int


def load_alpha(name: str) -> Image.Image:
    alpha = Image.open(FRAMES / f"{name}.png").convert("RGBA").split()[-1]
    side = round(alpha.width * SCALE)
    return alpha.resize((side, side), Image.LANCZOS)


def even_box(x0: int, y0: int, x1: int, y1: int) -> Box:
    """Grow a half-open pixel range outward until it starts even and has even size."""
    x0 -= x0 % 2
    y0 -= y0 % 2
    return Box(x0, y0, (x1 - x0 + 1) // 2 * 2, (y1 - y0 + 1) // 2 * 2)


def union_bbox(images: list[Image.Image]) -> tuple[int, int, int, int]:
    boxes = [i.getbbox() for i in images]
    return (
        min(b[0] for b in boxes),
        min(b[1] for b in boxes),
        max(b[2] for b in boxes),
        max(b[3] for b in boxes),
    )


def differing_bbox(images: list[Image.Image]) -> tuple[int, int, int, int]:
    """Bounding box of every pixel that is not the same in all the images."""
    from PIL import ImageChops

    diff = Image.new("L", images[0].size, 0)
    for other in images[1:]:
        diff = ImageChops.lighter(diff, ImageChops.difference(images[0], other))
    box = diff.getbbox()
    assert box, "the poses are identical"
    return box


def crop(img: Image.Image, box: Box) -> Image.Image:
    return img.crop((box.x, box.y, box.x + box.w, box.y + box.h))


@dataclass
class Cat:
    canvas: Box  # where the cat sits in the 480 px frame
    base: Image.Image  # the rest frame with both holes cleared
    holes: dict[str, Box]  # relative to the canvas
    patches: dict[str, list[Image.Image]]


def build() -> Cat:
    names = sorted({n for poses in POSES.values() for n in poses})
    frames = {n: load_alpha(n) for n in names}
    x0, y0, x1, y1 = union_bbox(list(frames.values()))
    canvas = even_box(x0 - CANVAS_PAD, y0 - CANVAS_PAD, x1 + CANVAS_PAD, y1 + CANVAS_PAD)
    cropped = {n: crop(f, canvas) for n, f in frames.items()}

    holes: dict[str, Box] = {}
    patches: dict[str, list[Image.Image]] = {}
    base = cropped["rest"].copy()
    for part, poses in POSES.items():
        bx0, by0, bx1, by1 = differing_bbox([cropped[p] for p in poses])
        hole = even_box(bx0 - PATCH_PAD, by0 - PATCH_PAD, bx1 + PATCH_PAD, by1 + PATCH_PAD)
        holes[part] = hole
        patches[part] = [crop(cropped[p], hole) for p in poses]
        base.paste(0, (hole.x, hole.y, hole.x + hole.w, hole.y + hole.h))
    return Cat(canvas, base, holes, patches)


def compose(cat: Cat, ear: int = 0, tail: int = 0) -> Image.Image:
    """The canvas as the panel shows it: the still cat with one patch laid in each hole."""
    img = cat.base.copy()
    for part, pose in (("ear", ear), ("tail", tail)):
        hole = cat.holes[part]
        img.paste(cat.patches[part][pose], (hole.x, hole.y))
    return img


def c_array(name: str, img: Image.Image) -> str:
    data = img.tobytes()
    rows = []
    for i in range(0, len(data), 24):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 24]) + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n"


def c_dsc(arr: str, img: Image.Image, indent: str = "") -> str:
    w, h = img.size
    return (
        "{\n"
        f"{indent}    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        f"{indent}    .header.cf = LV_COLOR_FORMAT_A8,\n"
        f"{indent}    .header.w = {w},\n"
        f"{indent}    .header.h = {h},\n"
        f"{indent}    .header.stride = {w},\n"
        f"{indent}    .data_size = sizeof({arr}),\n"
        f"{indent}    .data = {arr},\n"
        f"{indent}}}"
    )


def geom_header(cat: Cat) -> str:
    lines = [
        "#pragma once",
        "",
        "/* Generated by firmware/scripts/gen_idle_cat.py. Do not edit. */",
        "",
        "/* The idle cat's canvas, and where it sits in the 480 px frame before centering. */",
        f"#define IDLE_CAT_W {cat.canvas.w}",
        f"#define IDLE_CAT_H {cat.canvas.h}",
        "/* Poses per moving part. Pose 0 is the cat at rest. */",
        "#define IDLE_CAT_POSES 3",
    ]
    for part, box in cat.holes.items():
        p = part.upper()
        lines += [
            f"/* The {part}'s patch box, relative to the canvas. */",
            f"#define IDLE_CAT_{p}_X {box.x}",
            f"#define IDLE_CAT_{p}_Y {box.y}",
            f"#define IDLE_CAT_{p}_W {box.w}",
            f"#define IDLE_CAT_{p}_H {box.h}",
        ]
    return "\n".join(lines) + "\n"


def source(cat: Cat) -> str:
    out = [
        '#include "idle_cat.h"',
        "",
        "/* Generated by firmware/scripts/gen_idle_cat.py from docs/branding/ginger-idle-anim.",
        " * Do not edit. A8 alpha, recolored by the UI. */",
        "",
        c_array("s_base_px", cat.base),
    ]
    for part, imgs in cat.patches.items():
        for i, img in enumerate(imgs):
            out.append(c_array(f"s_{part}_px_{i}", img))
    out.append(f"const lv_image_dsc_t idle_cat_base_img = {c_dsc('s_base_px', cat.base)};\n")
    for part, imgs in cat.patches.items():
        entries = [f"    {c_dsc(f's_{part}_px_{i}', img, '    ')}" for i, img in enumerate(imgs)]
        out.append(
            f"const lv_image_dsc_t idle_cat_{part}_img[IDLE_CAT_POSES] = {{\n"
            + ",\n".join(entries)
            + ",\n};\n"
        )
    return "\n".join(out)


def main() -> None:
    cat = build()
    (MAIN / "idle_cat_geom.h").write_text(geom_header(cat))
    (MAIN / "idle_cat.c").write_text(source(cat))
    print(f"canvas {cat.canvas.w}x{cat.canvas.h}, holes {cat.holes}")


if __name__ == "__main__":
    main()
