#!/usr/bin/env python3
"""Generate the link-down icon (an A8 alpha image) for the panel.

Renders docs/branding/ginger-linkdown/cat-off.svg and writes firmware/main/linkdown_icon.c.
Needs Pillow and rsvg-convert.   Usage: python3 gen_linkdown_icon.py
"""

from __future__ import annotations

import io
import re
import subprocess
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "branding" / "ginger-linkdown" / "cat-off.svg"
MAIN = ROOT / "firmware" / "main"


def icon_px() -> int:
    """The size the layout reserves for the icon (FACE_LINKDOWN_ICON in face_cover.h)."""
    header = (MAIN / "face_cover.h").read_text()
    return int(re.search(r"FACE_LINKDOWN_ICON\s*=\s*(\d+)", header).group(1))


def render() -> Image.Image:
    px = icon_px()
    png = subprocess.run(
        ["rsvg-convert", "-w", str(px), "-h", str(px), str(SOURCE)],
        check=True,
        capture_output=True,
    ).stdout
    return Image.open(io.BytesIO(png)).convert("RGBA").split()[-1]


def source(icon: Image.Image) -> str:
    data = icon.tobytes()
    rows = [
        "    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 24]) + ","
        for i in range(0, len(data), 24)
    ]
    w, h = icon.size
    return (
        '#include "icons.h"\n\n'
        "/* Generated by firmware/scripts/gen_linkdown_icon.py from\n"
        " * docs/branding/ginger-linkdown/cat-off.svg. Do not edit. A8 alpha, recolored by the UI. */\n\n"
        f"static const uint8_t s_linkdown_px[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n\n"
        "const lv_image_dsc_t desk_icon_linkdown = {\n"
        "    .header.magic = LV_IMAGE_HEADER_MAGIC,\n"
        "    .header.cf = LV_COLOR_FORMAT_A8,\n"
        f"    .header.w = {w},\n"
        f"    .header.h = {h},\n"
        f"    .header.stride = {w},\n"
        "    .data_size = sizeof(s_linkdown_px),\n"
        "    .data = s_linkdown_px,\n"
        "};\n"
    )


def main() -> None:
    icon = render()
    (MAIN / "linkdown_icon.c").write_text(source(icon))
    print(f"wrote linkdown_icon.c, {icon.size[0]}x{icon.size[1]}")


if __name__ == "__main__":
    main()
