#pragma once

/* Generated by firmware/scripts/gen_idle_cat.py. Do not edit. */

/* The idle cat's canvas, and where it sits in the 480 px frame before centering. */
#define IDLE_CAT_W 256
#define IDLE_CAT_H 194
/* Poses per moving part. Pose 0 is the cat at rest. */
#define IDLE_CAT_POSES 3
/* The ear's patch box, relative to the canvas. */
#define IDLE_CAT_EAR_X 30
#define IDLE_CAT_EAR_Y 2
#define IDLE_CAT_EAR_W 78
#define IDLE_CAT_EAR_H 42
/* The tail's patch box, relative to the canvas. */
#define IDLE_CAT_TAIL_X 52
#define IDLE_CAT_TAIL_Y 114
#define IDLE_CAT_TAIL_W 90
#define IDLE_CAT_TAIL_H 78
