#pragma once

/* Generated by firmware/scripts/gen_idle_cat.py. Do not edit. */

/* The idle cat's canvas, and where it sits in the 480 px frame before centering. */
#define IDLE_CAT_W 356
#define IDLE_CAT_H 268
/* Poses per moving part. Pose 0 is the cat at rest. */
#define IDLE_CAT_POSES 3
/* The ear's patch box, relative to the canvas. */
#define IDLE_CAT_EAR_X 42
#define IDLE_CAT_EAR_Y 2
#define IDLE_CAT_EAR_W 104
#define IDLE_CAT_EAR_H 52
/* The tail's patch box, relative to the canvas. */
#define IDLE_CAT_TAIL_X 74
#define IDLE_CAT_TAIL_Y 164
#define IDLE_CAT_TAIL_W 122
#define IDLE_CAT_TAIL_H 102
